import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';

const app = express();
app.use(cors());
app.use(express.json());

const ROOT = path.resolve();
const PROJECTS_DIR = path.join(ROOT, 'projects');
const DB_PATH = path.join(ROOT, 'db', 'projects.json');

function loadProjects() {
  if (!fs.existsSync(DB_PATH)) {
    fs.writeFileSync(DB_PATH, JSON.stringify({}, null, 2));
  }
  return JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));
}

function saveProjects(projects) {
  fs.writeFileSync(DB_PATH, JSON.stringify(projects, null, 2));
}

function createProjectScaffold(name) {
  const projectRoot = path.join(PROJECTS_DIR, name);
  const folders = [
    'src/design-system',
    'src/components',
    'src/tokens',
    'storybook',
    '__tests__'
  ];
  folders.forEach(f => fs.mkdirSync(path.join(projectRoot, f), { recursive: true }));
  // placeholder token file
  fs.writeFileSync(path.join(projectRoot, 'src/tokens/colors.js'),
    "export const colors = { primary: '#ff0000', secondary: '#00ff00' };\n");
  fs.writeFileSync(path.join(projectRoot, 'src/design-system/theme.js'),
    "import { colors } from '../tokens/colors';\nexport const theme = { colors, font: 'sans-serif', spacing: 8 };\n");
  const buttonComponent = `import React from 'react';\nimport { theme } from '../design-system/theme';\nexport const Button = ({ children, ...props }) => (\n  <button style={{ backgroundColor: theme.colors.primary, padding: theme.spacing }} {...props}>\n    {children}\n  </button>\n);\n`;
  fs.writeFileSync(path.join(projectRoot, 'src/components/Button.jsx'), buttonComponent);
  const inputComponent = `import React from 'react';\nexport const Input = props => <input {...props} />;\n`;
  fs.writeFileSync(path.join(projectRoot, 'src/components/Input.jsx'), inputComponent);
  const buttonStory = `import { Button } from '../src/components/Button';\nexport default { title: 'Button', component: Button };\nexport const Primary = () => <Button>Click me</Button>;\n`;
  fs.writeFileSync(path.join(projectRoot, 'storybook/Button.stories.jsx'), buttonStory);
  const testContent = `import { render } from '@testing-library/react';\nimport { Button } from '../src/components/Button';\ntest('renders button', () => {\n  render(<Button>test</Button>);\n});\n`;
  fs.writeFileSync(path.join(projectRoot, '__tests__/Button.test.jsx'), testContent);
}

app.get('/api/projects', (req, res) => {
  res.json(loadProjects());
});

app.post('/api/projects', (req, res) => {
  const { name, framework } = req.body;
  if (!name) return res.status(400).json({ error: 'name required' });
  const projects = loadProjects();
  if (projects[name]) return res.status(400).json({ error: 'exists' });
  projects[name] = { name, framework, createdAt: Date.now() };
  saveProjects(projects);
  createProjectScaffold(name);
  res.json(projects[name]);
});

app.post('/api/projects/:name/design-system', (req, res) => {
  const { name } = req.params;
  const settings = req.body;
  const projectRoot = path.join(PROJECTS_DIR, name);
  if (!fs.existsSync(projectRoot)) return res.status(404).json({ error: 'not found' });
  // save settings
  fs.writeFileSync(path.join(projectRoot, 'design-system.json'), JSON.stringify(settings, null, 2));
  res.json({ ok: true });
});

app.post('/api/projects/:name/components', (req, res) => {
  const { name } = req.params;
  const { componentName, prompt } = req.body;
  if (!componentName) return res.status(400).json({ error: 'componentName required' });
  const projectRoot = path.join(PROJECTS_DIR, name);
  const componentPath = path.join(projectRoot, `src/components/${componentName}.jsx`);
  if (fs.existsSync(componentPath)) return res.status(400).json({ error: 'component exists' });
  const placeholder = `// TODO: Generated by AI\nexport const ${componentName} = () => null;\n`;
  fs.writeFileSync(componentPath, placeholder);
  // story and test placeholders
  fs.writeFileSync(path.join(projectRoot, `storybook/${componentName}.stories.jsx`), `// TODO: story for ${componentName}\n`);
  fs.writeFileSync(path.join(projectRoot, `__tests__/${componentName}.test.jsx`), `// TODO: test for ${componentName}\n`);
  res.json({ ok: true });
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log('Server listening on', PORT));
