name: Welcome

on:
  issues:
    types:
      - opened
      - edited
    tags:
      - new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract project and content_type from issue description
      id: extract_values
      run: |
        FILE = "${{ github.event.issue.body }}"
        PROJECT=$(grep 'project:' $FILE | awk '{print $2}')
        echo "Project Name: $PROJECT"

        # Extract content type
        CONTENT_TYPE=$(grep 'content_type:' $FILE | awk '{print $2}')
        echo "Content Type: $CONTENT_TYPE"
        echo "project=$PROJECT" >> $GITHUB_OUTPUT
        echo "content_type=$CONTENT_TYPE" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        echo "${{ needs.extract_values.outputs.project }}--ppp"
        echo "${{ needs.extract_values.outputs.content_type }} --- ccc"
