name: Welcome

on:
  issues:
    types:
      - opened
      - edited
    tags:
      - new
  workflow_dispatch:
    inputs:
      project:
        type: string
      content_type:
        type: string
        default: scrollables

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.extract_values.outputs.project }}
      content_type: ${{ steps.extract_values.outputs.content_type }}
    steps:
    - name: Extract project and content_type from issue description
      id: extract_values
      run: |
        body="${{ github.event.issue.body }}"
        project_name=$(printf "%s\n" "$body" | grep "project:" | awk '{print $2}')
        echo "Project Name: jjj$project_name ooooo"
        
        # Extract content type the same way
        content_type=$(printf "%s\n" "$body" | grep "content_type:" | awk '{print $2}')
        echo "Content Type: iiii$content_type 0000"
        echo "project=$project_name" >> $GITHUB_OUTPUT
        echo "content_type=$content_type" >> $GITHUB_OUTPUT
        
  access:
    needs: build
    uses: ./.github/workflows/_test.yml
    with:
      PROJECT: ${{ needs.build.outputs.project || inputs.projects }} 
      CONTENT_TYPE: ${{ needs.build.outputs.content_type || inputs.content_type }}
        
    

    
