name: Welcome

on:
  issues:
    types:
      - opened
      - edited
    tags:
      - new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract project and content_type from issue description
      id: extract_values
      run: |
        body="${{ github.event.issue.body }}"
        project_name=$(printf "%s\n" "$body" | grep "project:" | awk '{print $2}')
        echo "Project Name: jjj$project_name ooooo"
        
        # Extract content type the same way
        content_type=$(printf "%s\n" "$body" | grep "content_type:" | awk '{print $2}')
        echo "Content Type: iiii$content_type 0000"
        

    - name: Build
      run: |
        echo "${{ needs.extract_values.outputs.project }}--ppp"
        echo "${{ needs.extract_values.outputs.content_type }} --- ccc"
